import type { Metadata } from 'next'
import Provider from '@/provider'
import '../../../public/globals.css'
import { notFound, redirect } from 'next/navigation'
import React from 'react'
import { AbstractIntlMessages } from 'use-intl'
import NavBar from '@/components/NavBar'
import { Jost } from 'next/font/google'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const roboto = Jost({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
})

const locales = ['en', 'ro']
export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  if (!locales.includes(locale as any)) {
    redirect('/en')
  }
  // const session = await auth()
  // if (!session) {
  //   //write the logic to redirect to /auth/signin in nextjs
  //   redirect('/api/auth/signin')
  // }

  let messages: AbstractIntlMessages
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }
  return (
    <html lang={locale} className={roboto.className}>
      <body>
        <Provider locale={locale} messages={messages}>
          <main className="flex flex-col items-center justify-between h-screen">
            <div className="flex w-full">
              <NavBar />
            </div>
            <div className="flex  w-full h-full flex-col grow">{children}</div>
          </main>
        </Provider>
      </body>
    </html>
  )
}
